# Generated by Django 3.1.3 on 2020-11-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='country',
            field=models.CharField(blank=True, choices=[('CaC', 'Choose a Country'), ('Al', 'Angola'), ('Ag', 'Afghanistan'), ('Agt', ' Argentina'), ('Aga', 'Algeria'), ('Ata', 'Australia'), ('Au', 'Austria'), ('bg', 'Belgium'), ('bf', 'Burkina-Faso'), ('bt', 'Botswana'), ('bl', 'Brazil'), ('ch', 'China'), ('co', 'Congo'), ('ca', 'Cameroon'), ('cu', 'Cuba'), ('dk', 'Denmark'), ('eg', 'Egypt'), ('ep', 'Ethiopia'), ('es', 'Estonia'), ('fr', 'France'), ('fj', 'Fiji'), ('fr', 'France'), ('gh', 'Ghana'), ('ga', 'Gabon'), ('gu', 'Guinea'), ('ger', 'Germany'), ('gra', 'Granada'), ('hong', 'Hong-Kong'), ('ha', 'Haiti'), ('hung', 'Hungary'), ('itl', 'Italy'), ('ido', 'Indonesia'), ('jpn', 'Japan'), ('ke', 'Kenya'), ('ku', 'Kuwait'), ('li', 'Liberia'), ('rw', 'Rwanda'), ('su', 'Sudan'), ('sou', 'South Africa'), ('tz', 'Tanzania'), ('ug', 'Uganda')], default='CaC', max_length=100),
        ),
    ]
